/* postfix */
export const FETCH = '_FETCH';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const SHOW = '_SHOW';
export const HIDE = '_HIDE';

export const START = '_START';
export const FINISH = '_FINISH';

export const INIT_UI = '_INIT_UI';

export const TOGGLE = '_TOGGLE';

export const VALIDATION_ERROR = '_VALIDATION_ERROR';

/* main part */
export const LOG_IN = 'LOG_IN';
export const DIALOG = 'DIALOG';
export const APP_LOADING = 'APP_LOADING';
export const SEARCH_PAGE = 'SEARCH_PAGE';
export const ORDER_DETAIL = 'ORDER_DETAIL';
export const HEADER_SHADOW = 'HEADER_SHADOW';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SUBMIT_CHECKOUT = 'SUBMIT_CHECKOUT';
export const CHECKOUT_ASK_PDF = 'CHECKOUT_ASK_PDF';
export const CART_PREVIEW = 'CART_PREVIEW';
export const CART_PREVIEW_CHANGE_ITEMS = 'CART_PREVIEW_CHANGE_ITEMS';
export const SETTINGS_ADDRESSES = 'SETTINGS_ADDRESSES';
export const RECENT_ORDERS = 'RECENT_ORDERS';
export const RECENT_ORDERS_CHANGE_PAGE = 'RECENT_ORDERS_CHANGE_PAGE';
export const MODIFY_MAILING_LIST = 'MODIFY_MAILING_LIST';
export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
export const CHANGE_CHECKOUT_DATA = 'CHANGE_CHECKOUT_DATA';
export const CHANGE_PAGE_PAGINATOR = 'CHANGE_PAGE_PAGINATOR';
export const CHECKOUT_STATIC = 'CHECKOUT_STATIC';
export const CHECKOUT_PRICING = 'CHECKOUT_PRICING';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';
export const MODIFY_SHIPPING_ADDRESS = 'MODIFY_SHIPPING_ADDRESS';
export const CHANGE_PAGINATION_LIMIT = 'CHANGE_PAGE_PAGINATION_LIMIT';
export const RECALCULATE_CHECKOUT_PRICE = 'RECALCULATE_CHECKOUT_PRICE';
export const INIT_CHECKED_CHECKOUT_DATA = 'INIT_CHECKED_CHECKOUT_DATA';
export const MODIFY_MAILING_LIST_REPROCESS = 'MODIFY_MAILING_LIST_REPROCESS';
export const MODIFY_MAILING_LIST_USE_CORRECT = 'MODIFY_MAILING_LIST_USE_CORRECT';
export const MODIFY_MAILING_LIST_SHOW_VALIDATION_ERRORS = 'MODIFY_MAILING_LIST_SHOW_VALIDATION_ERRORS';

/* env */
const DOMAIN = 'com';
