export const FETCH_SERVERS = 'SERVERS/FETCH_SERVERS';
export const FETCH_SERVERS_SUCCESS = 'SERVERS/FETCH_SERVERS_SUCCESS';
export const FETCH_SERVERS_FAILURE = 'SERVERS/FETCH_SERVERS_FAILURE';

export const LOGIN_CLIENT_VALIDATION_ERROR = 'LOGIN/LOGIN_CLIENT_VALIDATION_ERROR';
export const LOGIN_RESPONSE_SUCCESS = 'LOGIN/LOGIN_RESPONSE_SUCCESS';
export const LOGIN_RESPONSE_FAILURE = 'LOGIN/LOGIN_RESPONSE_FAILURE';

export const MAILING_RESPONSE_SUCCESS = 'MAILING/MAILING_RESPONSE_SUCCESS';

export const SHOPPING_CART_UI_FETCH = 'SHOPPING_CART_UI_FETCH';
export const SHOPPING_CART_UI_SUCCESS = 'SHOPPING_CART_UI_SUCCESS';
export const SHOPPING_CART_UI_FAILURE = 'SHOPPING_CART_UI_FAILURE';

export const CHANGE_SHOPPING_DATA = 'CHANGE_SHOPPING_DATA';
export const INIT_CHECKED_SHOPPING_DATA = 'INIT_CHECKED_SHOPPING_DATA';

export const RECALCULATE_SHIPPING_PRICE_FETCH = 'RECALCULATE_SHIPPING_PRICE_FETCH';
export const RECALCULATE_SHIPPING_PRICE_SUCCESS = 'RECALCULATE_SHIPPING_PRICE_SUCCESS';
export const RECALCULATE_SHIPPING_PRICE_FAILURE = 'RECALCULATE_SHIPPING_PRICE_FAILURE';

export const SEND_SHIPPING_DATA_FETCH = 'SEND_SHIPPING_DATA_FETCH';
export const SEND_SHIPPING_DATA_FAILURE = 'SEND_SHIPPING_DATA_FAILURE';
export const SEND_SHIPPING_DATA_SUCCESS = 'SEND_SHIPPING_DATA_SUCCESS';

export const ERROR_SHIPPING_VALIDATION = 'ERROR_SHIPPING_VALIDATION';
