export const LOGIN_CLIENT_FETCH = 'LOGIN_CLIENT_FETCH';
export const LOGIN_CLIENT_SUCCESS = 'LOGIN_CLIENT_SUCCESS';
export const LOGIN_CLIENT_FAILURE = 'LOGIN_CLIENT_FAILURE';

export const LOGIN_CLIENT_VALIDATION_ERROR = 'LOGIN/LOGIN_CLIENT_VALIDATION_ERROR';

export const MAILING_RESPONSE_SUCCESS = 'MAILING/MAILING_RESPONSE_SUCCESS';

export const SHOPPING_CART_UI_FETCH = 'SHOPPING_CART_UI_FETCH';
export const SHOPPING_CART_UI_SUCCESS = 'SHOPPING_CART_UI_SUCCESS';
export const SHOPPING_CART_UI_FAILURE = 'SHOPPING_CART_UI_FAILURE';

export const CHANGE_SHOPPING_DATA = 'CHANGE_SHOPPING_DATA';
export const INIT_CHECKED_SHOPPING_DATA = 'INIT_CHECKED_SHOPPING_DATA';

export const RECALCULATE_SHOPPING_PRICE_FETCH = 'RECALCULATE_SHOPPING_PRICE_FETCH';
export const RECALCULATE_SHOPPING_PRICE_SUCCESS = 'RECALCULATE_SHOPPING_PRICE_SUCCESS';
export const RECALCULATE_SHOPPING_PRICE_FAILURE = 'RECALCULATE_SHOPPING_PRICE_FAILURE';

export const SEND_SHOPPING_DATA_FETCH = 'SEND_SHOPPING_DATA_FETCH';
export const SEND_SHOPPING_DATA_FAILURE = 'SEND_SHOPPING_DATA_FAILURE';
export const SEND_SHOPPING_DATA_SUCCESS = 'SEND_SHOPPING_DATA_SUCCESS';

export const REMOVE_PRODUCT_FETCH = 'REMOVE_PRODUCT_FETCH';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE';

export const CHANGE_PRODUCT_QUANTITY_FETCH = 'CHANGE_PRODUCT_QUANTITY_FETCH';
export const CHANGE_PRODUCT_QUANTITY_FAILURE = 'CHANGE_PRODUCT_QUANTITY_FAILURE';
export const CHANGE_PRODUCT_QUANTITY_SUCCESS = 'CHANGE_PRODUCT_QUANTITY_SUCCESS';

export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_LOADING_FINISH = 'APP_LOADING_FINISH';

export const SETTINGS_ADDRESSES_UI_FETCH = 'SETTINGS_ADDRESSES_UI_FETCH';
export const SETTINGS_ADDRESSES_UI_SUCCESS = 'SETTINGS_ADDRESSES_UI_SUCCESS';
export const SETTINGS_ADDRESSES_UI_FAILURE = 'SETTINGS_ADDRESSES_UI_FAILURE';

export const DIALOG_OPEN = 'DIALOG_OPEN';
export const DIALOG_CLOSE = 'DIALOG_CLOSE';

export const MODIFY_SHIPPING_ADDRESS_FETCH = 'MODIFY_SHIPPING_ADDRESS_FETCH';
export const MODIFY_SHIPPING_ADDRESS_SUCCESS = 'MODIFY_SHIPPING_ADDRESS_SUCCESS';
export const MODIFY_SHIPPING_ADDRESS_FAILURE = 'MODIFY_SHIPPING_ADDRESS_FAILURE';

export const ORDER_DETAIL_GET_UI_FETCH = 'ORDER_DETAIL_GET_UI_FETCH';
export const ORDER_DETAIL_GET_UI_SUCCESS = 'ORDER_DETAIL_GET_UI_SUCCESS';
export const ORDER_DETAIL_GET_UI_FAILURE = 'ORDER_DETAIL_GET_UI_FAILURE';

export const SEARCH_PAGE_UI_FETCHING = 'SEARCH_PAGE_UI_FETCHING';
export const SEARCH_PAGE_UI_SUCCESS = 'SEARCH_PAGE_UI_SUCCESS';
export const SEARCH_PAGE_UI_FAILURE = 'SEARCH_PAGE_UI_FAILURE';

export const CHANGE_PAGE_PAGINATOR = 'CHANGE_PAGE_PAGINATOR';

export const CHANGE_PAGE_PAGINATION_LIMIT = 'CHANGE_PAGE_PAGINATION_LIMIT';

export const SEARCH_RESULTS_HIDE = 'SEARCH_RESULTS_HIDE';
export const SEARCH_RESULTS_SHOW = 'SEARCH_RESULTS_SHOW';

export const SEARCH_RESULT_GET_SUCCESS = 'SEARCH_RESULT_GET_SUCCESS';
export const SEARCH_RESULT_GET_FAILURE = 'SEARCH_RESULT_GET_FAILURE';
export const SEARCH_RESULT_GET_FETCH = 'SEARCH_RESULT_GET_FETCH';

export const SEARCH_QUERY_CHANGE = 'SEARCH_QUERY_CHANGE';

export const HEADER_SHADOW_SHOW = 'HEADER_SHADOW_SHOW';
export const HEADER_SHADOW_HIDE = 'HEADER_SHADOW_HIDE';

export const GET_RECENT_ORDERS_HEADINGS_FETCH = 'GET_RECENT_ORDERS_HEADINGS_FETCH';
export const GET_RECENT_ORDERS_ROWS_FETCH = 'GET_RECENT_ORDERS_ROWS_FETCH';
export const GET_RECENT_ORDERS_HEADINGS_SUCCESS = 'GET_RECENT_ORDERS_HEADINGS_SUCCESS';
export const GET_RECENT_ORDERS_ROWS_SUCCESS = 'GET_RECENT_ORDERS_ROWS_SUCCESS';
export const GET_RECENT_ORDERS_HEADINGS_FAILURE = 'GET_RECENT_ORDERS_HEADINGS_FAILURE';
export const GET_RECENT_ORDERS_ROWS_FAILURE = 'GET_RECENT_ORDERS_ROWS_FAILURE';

export const CHECKOUT_ASK_PDF_FETCH = 'CHECKOUT_ASK_PDF_FETCH';
export const CHECKOUT_ASK_PDF_SUCCESS = 'CHECKOUT_ASK_PDF_SUCCESS';
export const CHECKOUT_ASK_PDF_FAILURE = 'CHECKOUT_ASK_PDF_FAILURE';
