//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(BrandItem.CLASS_NAME, typeof(BrandItem))]

namespace CMS.CustomTables.Types.KDA
{
    /// <summary>
    /// Represents a content item of type BrandItem.
    /// </summary>
    public partial class BrandItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "KDA.Brand";


        /// <summary>
        /// The instance of the class that provides extended API for working with BrandItem fields.
        /// </summary>
        private readonly BrandItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Brand Code.
        /// </summary>
        [DatabaseField]
        public int BrandCode
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("BrandCode"), 0);
            }
            set
            {
                SetValue("BrandCode", value);
            }
        }


        /// <summary>
        /// Brand Name.
        /// </summary>
        [DatabaseField]
        public string BrandName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BrandName"), "");
            }
            set
            {
                SetValue("BrandName", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string BrandDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BrandDescription"), "");
            }
            set
            {
                SetValue("BrandDescription", value);
            }
        }


        /// <summary>
        /// Status.
        /// </summary>
        [DatabaseField]
        public bool Status
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("Status"), true);
            }
            set
            {
                SetValue("Status", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with BrandItem fields.
        /// </summary>
        [RegisterProperty]
        public BrandItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with BrandItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class BrandItemFields : AbstractHierarchicalObject<BrandItemFields>
        {
            /// <summary>
            /// The content item of type BrandItem that is a target of the extended API.
            /// </summary>
            private readonly BrandItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="BrandItemFields" /> class with the specified content item of type BrandItem.
            /// </summary>
            /// <param name="instance">The content item of type BrandItem that is a target of the extended API.</param>
            public BrandItemFields(BrandItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Brand Code.
            /// </summary>
            public int BrandCode
            {
                get
                {
                    return mInstance.BrandCode;
                }
                set
                {
                    mInstance.BrandCode = value;
                }
            }


            /// <summary>
            /// Brand Name.
            /// </summary>
            public string BrandName
            {
                get
                {
                    return mInstance.BrandName;
                }
                set
                {
                    mInstance.BrandName = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string BrandDescription
            {
                get
                {
                    return mInstance.BrandDescription;
                }
                set
                {
                    mInstance.BrandDescription = value;
                }
            }


            /// <summary>
            /// Status.
            /// </summary>
            public bool Status
            {
                get
                {
                    return mInstance.Status;
                }
                set
                {
                    mInstance.Status = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="BrandItem" /> class.
        /// </summary>
        public BrandItem() : base(CLASS_NAME)
        {
            mFields = new BrandItemFields(this);
        }

        #endregion
    }
}