//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(DivisionItem.CLASS_NAME, typeof(DivisionItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type DivisionItem.
	/// </summary>
	public partial class DivisionItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.Division";


		/// <summary>
		/// The instance of the class that provides extended API for working with DivisionItem fields.
		/// </summary>
		private readonly DivisionItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Division Name.
		/// </summary>
		[DatabaseField]
		public string DivisionName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DivisionName"), "");
			}
			set
			{
				SetValue("DivisionName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DivisionItem fields.
		/// </summary>
		[RegisterProperty]
		public DivisionItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with DivisionItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DivisionItemFields : AbstractHierarchicalObject<DivisionItemFields>
		{
			/// <summary>
			/// The content item of type DivisionItem that is a target of the extended API.
			/// </summary>
			private readonly DivisionItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DivisionItemFields" /> class with the specified content item of type DivisionItem.
			/// </summary>
			/// <param name="instance">The content item of type DivisionItem that is a target of the extended API.</param>
			public DivisionItemFields(DivisionItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Division Name.
			/// </summary>
			public string DivisionName
			{
				get
				{
					return mInstance.DivisionName;
				}
				set
				{
					mInstance.DivisionName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DivisionItem" /> class.
		/// </summary>
		public DivisionItem() : base(CLASS_NAME)
		{
			mFields = new DivisionItemFields(this);
		}

		#endregion
	}
}