//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(UserBusinessUnitsItem.CLASS_NAME, typeof(UserBusinessUnitsItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type UserBusinessUnitsItem.
	/// </summary>
	public partial class UserBusinessUnitsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.UserBusinessUnits";


		/// <summary>
		/// The instance of the class that provides extended API for working with UserBusinessUnitsItem fields.
		/// </summary>
		private readonly UserBusinessUnitsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// User ID.
		/// </summary>
		[DatabaseField]
		public int UserID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("UserID"), 0);
			}
			set
			{
				SetValue("UserID", value);
			}
		}


		/// <summary>
		/// Business Unit Item ID.
		/// </summary>
		[DatabaseField]
		public int BusinessUnitID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BusinessUnitID"), 0);
			}
			set
			{
				SetValue("BusinessUnitID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with UserBusinessUnitsItem fields.
		/// </summary>
		[RegisterProperty]
		public UserBusinessUnitsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with UserBusinessUnitsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class UserBusinessUnitsItemFields : AbstractHierarchicalObject<UserBusinessUnitsItemFields>
		{
			/// <summary>
			/// The content item of type UserBusinessUnitsItem that is a target of the extended API.
			/// </summary>
			private readonly UserBusinessUnitsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="UserBusinessUnitsItemFields" /> class with the specified content item of type UserBusinessUnitsItem.
			/// </summary>
			/// <param name="instance">The content item of type UserBusinessUnitsItem that is a target of the extended API.</param>
			public UserBusinessUnitsItemFields(UserBusinessUnitsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// User ID.
			/// </summary>
			public int UserID
			{
				get
				{
					return mInstance.UserID;
				}
				set
				{
					mInstance.UserID = value;
				}
			}


			/// <summary>
			/// Business Unit Item ID.
			/// </summary>
			public int BusinessUnitID
			{
				get
				{
					return mInstance.BusinessUnitID;
				}
				set
				{
					mInstance.BusinessUnitID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="UserBusinessUnitsItem" /> class.
		/// </summary>
		public UserBusinessUnitsItem() : base(CLASS_NAME)
		{
			mFields = new UserBusinessUnitsItemFields(this);
		}

		#endregion
	}
}