//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(UserFYBudgetAllocationItem.CLASS_NAME, typeof(UserFYBudgetAllocationItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type UserFYBudgetAllocationItem.
	/// </summary>
	public partial class UserFYBudgetAllocationItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.UserFYBudgetAllocation";


		/// <summary>
		/// The instance of the class that provides extended API for working with UserFYBudgetAllocationItem fields.
		/// </summary>
		private readonly UserFYBudgetAllocationItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// User Remaining Budget.
        /// </summary>
        [DatabaseField]
        public double UserRemainingBudget
        {
            get
            {
                return ValidationHelper.GetDouble(GetValue("UserRemainingBudget"), 0);
            }
            set
            {
                SetValue("UserRemainingBudget", value);
            }
        }

        /// <summary>
        /// Year.
        /// </summary>
        [DatabaseField]
		public string Year
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Year"), "");
			}
			set
			{
				SetValue("Year", value);
			}
		}


		/// <summary>
		/// User.
		/// </summary>
		[DatabaseField]
		public int UserID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("UserID"), 0);
			}
			set
			{
				SetValue("UserID", value);
			}
		}


		/// <summary>
		/// Budget.
		/// </summary>
		[DatabaseField]
		public double Budget
		{
			get
			{
				return ValidationHelper.GetDouble(GetValue("Budget"), 0);
			}
			set
			{
				SetValue("Budget", value);
			}
		}


		/// <summary>
		/// Site.
		/// </summary>
		[DatabaseField]
		public int SiteID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SiteID"), 0);
			}
			set
			{
				SetValue("SiteID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with UserFYBudgetAllocationItem fields.
		/// </summary>
		[RegisterProperty]
		public UserFYBudgetAllocationItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with UserFYBudgetAllocationItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class UserFYBudgetAllocationItemFields : AbstractHierarchicalObject<UserFYBudgetAllocationItemFields>
		{
			/// <summary>
			/// The content item of type UserFYBudgetAllocationItem that is a target of the extended API.
			/// </summary>
			private readonly UserFYBudgetAllocationItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="UserFYBudgetAllocationItemFields" /> class with the specified content item of type UserFYBudgetAllocationItem.
			/// </summary>
			/// <param name="instance">The content item of type UserFYBudgetAllocationItem that is a target of the extended API.</param>
			public UserFYBudgetAllocationItemFields(UserFYBudgetAllocationItem instance)
			{
				mInstance = instance;
			}

            /// <summary>
			/// User Remaining Budget.
			/// </summary>
			public double UserRemainingBudget
            {
                get
                {
                    return mInstance.UserRemainingBudget;
                }
                set
                {
                    mInstance.UserRemainingBudget = value;
                }
            }

            /// <summary>
            /// Year.
            /// </summary>
            public string Year
			{
				get
				{
					return mInstance.Year;
				}
				set
				{
					mInstance.Year = value;
				}
			}


			/// <summary>
			/// User.
			/// </summary>
			public int UserID
			{
				get
				{
					return mInstance.UserID;
				}
				set
				{
					mInstance.UserID = value;
				}
			}


			/// <summary>
			/// Budget.
			/// </summary>
			public double Budget
			{
				get
				{
					return mInstance.Budget;
				}
				set
				{
					mInstance.Budget = value;
				}
			}


			/// <summary>
			/// Site.
			/// </summary>
			public int SiteID
			{
				get
				{
					return mInstance.SiteID;
				}
				set
				{
					mInstance.SiteID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="UserFYBudgetAllocationItem" /> class.
		/// </summary>
		public UserFYBudgetAllocationItem() : base(CLASS_NAME)
		{
			mFields = new UserFYBudgetAllocationItemFields(this);
		}

		#endregion
	}
}