using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutomatedTests.KenticoApi.Objects
{
    public class CmsDocument
    {
        // SKU parts
        //public object ProductRelatedSKUs { get; set; }
        //public bool SKUEnabled { get; set; }
        //public object SKUAvailableInDays { get; set; }
        //public string SKUNumber { get; set; }
        //public object SKUPrivateDonation { get; set; }
        //public int SKUSiteID { get; set; }
        //public object SKUCustomData { get; set; }
        //public string SKUName { get; set; }
        //public object SKUOrder { get; set; }
        //public object SKUWeight { get; set; }
        //public bool SKUSellOnlyAvailable { get; set; }
        //public object SKUBundleItemsCount { get; set; }
        //public object SKUValidUntil { get; set; }
        //public DateTime SKUInStoreFrom { get; set; }
        //public object DocumentSKUShortDescription { get; set; }
        //public object SKUDepartmentID { get; set; }
        //public string SKUImagePath { get; set; }
        //public object SKUDepth { get; set; }
        //public object SKUWidth { get; set; }
        //public string DocumentSKUName { get; set; }
        //public bool SKUNeedsShipping { get; set; }
        //public object SKUValidity { get; set; }
        //public object SKUHeight { get; set; }
        //public object SKURetailPrice { get; set; }
        //public object SKUEproductFilesCount { get; set; }
        //public string SKUTrackInventory { get; set; }
        //public string SKUGUID { get; set; }
        //public object SKUMaxItemsInOrder { get; set; }
        //public object SKUAvailableItems { get; set; }
        //public int SKUID { get; set; }
        //public object SKUMinItemsInOrder { get; set; }
        //public int SKUPrice { get; set; }
        //public object SKUMaxPrice { get; set; }
        //public DateTime SKUCreated { get; set; }
        //public object SKUParentSKUID { get; set; }
        //public object SKUPublicStatusID { get; set; }
        //public int NodeSKUID { get; set; }
        //public object SKUMinPrice { get; set; }
        //public object SKUInternalStatusID { get; set; }
        //public object SKUManufacturerID { get; set; }
        //public object SKUReorderAt { get; set; }
        //public object SKUShortDescription { get; set; }
        //public object SKUConversionName { get; set; }
        //public object SKUSupplierID { get; set; }
        //public object SKUBundleInventoryType { get; set; }
        //public string SKUProductType { get; set; }
        //public object DocumentSKUDescription { get; set; }
        //public object SKUMembershipGUID { get; set; }
        //public object SKUValidFor { get; set; }
        //public object SKUOptionCategoryID { get; set; }
        //public object SKUDescription { get; set; }
        //public DateTime SKULastModified { get; set; }
        //public string SKUConversionValue { get; set; }

        // Other
        public object NodeAllowCacheInFileSystem { get; set; }
        public object DocumentCheckedOutByUserID { get; set; }
        public bool NodeIsContentOnly { get; set; }
        public object NodeCustomData { get; set; }
        public object DocumentLastPublished { get; set; }
        public int? DocumentPageTemplateID { get; set; }
        public bool NodeHasLinks { get; set; }
        public DateTime DocumentCreatedWhen { get; set; }
        public DateTime DocumentCheckedOutWhen { get; set; }
        public string DocumentGUID { get; set; }
        public bool NodeIsACLOwner { get; set; }
        public object DocumentExtensions { get; set; }
        public string DocumentMenuCaption { get; set; }
        public bool DocumentShowInSiteMap { get; set; }
        public string DocumentCulture { get; set; }
        public object DocumentLogVisitActivity { get; set; }
        public bool DocumentMenuItemInactive { get; set; }
        public object DocumentConversionValue { get; set; }
        public object DocumentPageTitle { get; set; }
        public int DocumentModifiedByUserID { get; set; }
        public string DocumentWorkflowCycleGUID { get; set; }
        public object DocumentCheckedOutAutomatically { get; set; }
        public object DocumentWorkflowActionStatus { get; set; }
        public string DocumentMenuClass { get; set; }
        public object DocumentCheckedOutVersionHistoryID { get; set; }
        public int NodeSiteID { get; set; }
        public int DocumentForeignKeyValue { get; set; }
        public string DocumentUrlPath { get; set; }
        public bool DocumentMenuItemHideInNavigation { get; set; }
        public object NodeBodyScripts { get; set; }
        public object NodeLinkedNodeSiteID { get; set; }
        public int DocumentID { get; set; }
        public bool IsSecuredNode { get; set; }
        public string NodeAlias { get; set; }
        public string DocumentNamePath { get; set; }
        public object DocumentLastVersionNumber { get; set; }
        public int NodeOrder { get; set; }
        public string DocumentMenuClassHighlighted { get; set; }
        public DateTime DocumentModifiedWhen { get; set; }
        public int NodeOwner { get; set; }
        public string NodeName { get; set; }
        public string DocumentMenuStyle { get; set; }
        public bool DocumentIsArchived { get; set; }
        public string DocumentMenuItemRightImageHighlighted { get; set; }
        public bool DocumentCanBePublished { get; set; }
        public string DocumentMenuRedirectUrl { get; set; }
        public object DocumentUseCustomExtensions { get; set; }
        public object DocumentStylesheetID { get; set; }
        public object NodeDocType { get; set; }
        public string DocumentMenuItemLeftImage { get; set; }
        public object DocumentPageKeyWords { get; set; }
        public object RequiresSSL { get; set; }
        public string DocumentMenuItemLeftImageHighlighted { get; set; }
        public int NodeID { get; set; }
        public int DocumentPriority { get; set; }
        public int NodeOriginalNodeID { get; set; }
        public object DocumentHash { get; set; }
        public bool NodeTemplateForAllCultures { get; set; }
        public string DocumentMenuItemImage { get; set; }
        public object DocumentCustomData { get; set; }
        public object DocumentPublishFrom { get; set; }
        public object NodeBodyElementAttributes { get; set; }
        public object NodeHeadTags { get; set; }
        public bool DocumentSearchExcluded { get; set; }
        public object DocumentGroupWebParts { get; set; }
        public string DocumentMenuJavascript { get; set; }
        public string DocumentMenuStyleHighlighted { get; set; }
        public object DocumentPublishedVersionHistoryID { get; set; }
        public bool DocumentInheritsStylesheet { get; set; }
        public int NodeClassID { get; set; }
        public string DocumentContent { get; set; }
        public string DocumentMenuItemImageHighlighted { get; set; }
        public object DocumentIsWaitingForTranslation { get; set; }
        public object DocumentTags { get; set; }
        public int NodeACLID { get; set; }
        public object DocumentWorkflowStepID { get; set; }
        public object NodeLinkedNodeID { get; set; }
        public object DocumentPageDescription { get; set; }
        public bool NodeHasChildren { get; set; }
        public string DocumentWildcardRule { get; set; }
        public bool DocumentMenuRedirectToFirstChild { get; set; }
        public object DocumentPublishTo { get; set; }
        public object DocumentRatings { get; set; }
        public bool DocumentUseNamePathForUrlPath { get; set; }
        public object DocumentRatingValue { get; set; }
        public string NodeGUID { get; set; }
        public string NodeInheritPageLevels { get; set; }
        public int DocumentNodeID { get; set; }
        public string ClassName { get; set; }
        public string ClassDisplayName { get; set; }
        public object DocumentWebParts { get; set; }
        public object DocumentTagGroupID { get; set; }
        public string DocumentName { get; set; }
        public object DocumentTrackConversionName { get; set; }
        public string NodeAliasPath { get; set; }
        public string DocumentSitemapSettings { get; set; }
        public object DocumentType { get; set; }
        public object NodeCacheMinutes { get; set; }
        public int? NodeLevel { get; set; }
        public int? DocumentCreatedByUserID { get; set; }
        public object NodeGroupID { get; set; }
        public int? NodeParentID { get; set; }
        public string DocumentMenuItemRightImage { get; set; }
        public int? NodeTemplateID { get; set; }
        public bool NodeInheritPageTemplate { get; set; }

    }
}
