//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(BusinessUnitItem.CLASS_NAME, typeof(BusinessUnitItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type BusinessUnitItem.
	/// </summary>
	public partial class BusinessUnitItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.BusinessUnit";


		/// <summary>
		/// The instance of the class that provides extended API for working with BusinessUnitItem fields.
		/// </summary>
		private readonly BusinessUnitItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Business Unit Number.
		/// </summary>
		[DatabaseField]
		public long BusinessUnitNumber
		{
			get
			{
				return ValidationHelper.GetLong(GetValue("BusinessUnitNumber"), 0);
			}
			set
			{
				SetValue("BusinessUnitNumber", value);
			}
		}


		/// <summary>
		/// Business Unit Name.
		/// </summary>
		[DatabaseField]
		public string BusinessUnitName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BusinessUnitName"), "");
			}
			set
			{
				SetValue("BusinessUnitName", value);
			}
		}


		/// <summary>
		/// Business Unit Status.
		/// </summary>
		[DatabaseField]
		public bool Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Status"), false);
			}
			set
			{
				SetValue("Status", value);
			}
		}


		/// <summary>
		/// Site ID.
		/// </summary>
		[DatabaseField]
		public int SiteID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SiteID"), 0);
			}
			set
			{
				SetValue("SiteID", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BusinessUnitItem fields.
		/// </summary>
		[RegisterProperty]
		public BusinessUnitItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BusinessUnitItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BusinessUnitItemFields : AbstractHierarchicalObject<BusinessUnitItemFields>
		{
			/// <summary>
			/// The content item of type BusinessUnitItem that is a target of the extended API.
			/// </summary>
			private readonly BusinessUnitItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BusinessUnitItemFields" /> class with the specified content item of type BusinessUnitItem.
			/// </summary>
			/// <param name="instance">The content item of type BusinessUnitItem that is a target of the extended API.</param>
			public BusinessUnitItemFields(BusinessUnitItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Business Unit Number.
			/// </summary>
			public long BusinessUnitNumber
			{
				get
				{
					return mInstance.BusinessUnitNumber;
				}
				set
				{
					mInstance.BusinessUnitNumber = value;
				}
			}


			/// <summary>
			/// Business Unit Name.
			/// </summary>
			public string BusinessUnitName
			{
				get
				{
					return mInstance.BusinessUnitName;
				}
				set
				{
					mInstance.BusinessUnitName = value;
				}
			}


			/// <summary>
			/// Business Unit Status.
			/// </summary>
			public bool Status
			{
				get
				{
					return mInstance.Status;
				}
				set
				{
					mInstance.Status = value;
				}
			}


			/// <summary>
			/// Site ID.
			/// </summary>
			public int SiteID
			{
				get
				{
					return mInstance.SiteID;
				}
				set
				{
					mInstance.SiteID = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BusinessUnitItem" /> class.
		/// </summary>
		public BusinessUnitItem() : base(CLASS_NAME)
		{
			mFields = new BusinessUnitItemFields(this);
		}

		#endregion
	}
}