//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(FailedOrdersItem.CLASS_NAME, typeof(FailedOrdersItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type FailedOrdersItem.
	/// </summary>
	public partial class FailedOrdersItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.FailedOrders";


		/// <summary>
		/// The instance of the class that provides extended API for working with FailedOrdersItem fields.
		/// </summary>
		private readonly FailedOrdersItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Campaign ID.
		/// </summary>
		[DatabaseField]
		public int CampaignID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CampaignID"), 0);
			}
			set
			{
				SetValue("CampaignID", value);
			}
		}


		/// <summary>
		/// Is Campaign Orders In Progress.
		/// </summary>
		[DatabaseField]
		public bool IsCampaignOrdersInProgress
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsCampaignOrdersInProgress"), false);
			}
			set
			{
				SetValue("IsCampaignOrdersInProgress", value);
			}
		}


		/// <summary>
		/// Is Campaign Orders Failed.
		/// </summary>
		[DatabaseField]
		public bool IsCampaignOrdersFailed
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsCampaignOrdersFailed"), false);
			}
			set
			{
				SetValue("IsCampaignOrdersFailed", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FailedOrdersItem fields.
		/// </summary>
		[RegisterProperty]
		public FailedOrdersItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FailedOrdersItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FailedOrdersItemFields : AbstractHierarchicalObject<FailedOrdersItemFields>
		{
			/// <summary>
			/// The content item of type FailedOrdersItem that is a target of the extended API.
			/// </summary>
			private readonly FailedOrdersItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FailedOrdersItemFields" /> class with the specified content item of type FailedOrdersItem.
			/// </summary>
			/// <param name="instance">The content item of type FailedOrdersItem that is a target of the extended API.</param>
			public FailedOrdersItemFields(FailedOrdersItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Campaign ID.
			/// </summary>
			public int CampaignID
			{
				get
				{
					return mInstance.CampaignID;
				}
				set
				{
					mInstance.CampaignID = value;
				}
			}


			/// <summary>
			/// Is Campaign Orders In Progress.
			/// </summary>
			public bool IsCampaignOrdersInProgress
			{
				get
				{
					return mInstance.IsCampaignOrdersInProgress;
				}
				set
				{
					mInstance.IsCampaignOrdersInProgress = value;
				}
			}


			/// <summary>
			/// Is Campaign Orders Failed.
			/// </summary>
			public bool IsCampaignOrdersFailed
			{
				get
				{
					return mInstance.IsCampaignOrdersFailed;
				}
				set
				{
					mInstance.IsCampaignOrdersFailed = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FailedOrdersItem" /> class.
		/// </summary>
		public FailedOrdersItem() : base(CLASS_NAME)
		{
			mFields = new FailedOrdersItemFields(this);
		}

		#endregion
	}
}