//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(FiscalYearManagementItem.CLASS_NAME, typeof(FiscalYearManagementItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type FiscalYearManagementItem.
	/// </summary>
	public partial class FiscalYearManagementItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.FiscalYearManagement";


		/// <summary>
		/// The instance of the class that provides extended API for working with FiscalYearManagementItem fields.
		/// </summary>
		private readonly FiscalYearManagementItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Year.
		/// </summary>
		[DatabaseField]
		public string Year
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Year"), "{%DateTime.Now.Year|(user)cvoqa2@gmail.com|(hash)a3f13b3815baa25cc593f85f4852a84761453707f9d76747eb6866bc412a9777%}");
			}
			set
			{
				SetValue("Year", value);
			}
		}


		/// <summary>
		/// Fiscal Year Start Date.
		/// </summary>
		[DatabaseField]
		public DateTime FiscalYearStartDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("FiscalYearStartDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("FiscalYearStartDate", value);
			}
		}


		/// <summary>
		/// Fiscal Year End Date.
		/// </summary>
		[DatabaseField]
		public DateTime FiscalYearEndDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("FiscalYearEndDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("FiscalYearEndDate", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with FiscalYearManagementItem fields.
		/// </summary>
		[RegisterProperty]
		public FiscalYearManagementItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with FiscalYearManagementItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class FiscalYearManagementItemFields : AbstractHierarchicalObject<FiscalYearManagementItemFields>
		{
			/// <summary>
			/// The content item of type FiscalYearManagementItem that is a target of the extended API.
			/// </summary>
			private readonly FiscalYearManagementItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="FiscalYearManagementItemFields" /> class with the specified content item of type FiscalYearManagementItem.
			/// </summary>
			/// <param name="instance">The content item of type FiscalYearManagementItem that is a target of the extended API.</param>
			public FiscalYearManagementItemFields(FiscalYearManagementItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Year.
			/// </summary>
			public string Year
			{
				get
				{
					return mInstance.Year;
				}
				set
				{
					mInstance.Year = value;
				}
			}


			/// <summary>
			/// Fiscal Year Start Date.
			/// </summary>
			public DateTime FiscalYearStartDate
			{
				get
				{
					return mInstance.FiscalYearStartDate;
				}
				set
				{
					mInstance.FiscalYearStartDate = value;
				}
			}


			/// <summary>
			/// Fiscal Year End Date.
			/// </summary>
			public DateTime FiscalYearEndDate
			{
				get
				{
					return mInstance.FiscalYearEndDate;
				}
				set
				{
					mInstance.FiscalYearEndDate = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="FiscalYearManagementItem" /> class.
		/// </summary>
		public FiscalYearManagementItem() : base(CLASS_NAME)
		{
			mFields = new FiscalYearManagementItemFields(this);
		}

		#endregion
	}
}