//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(IBTFAdjustmentItem.CLASS_NAME, typeof(IBTFAdjustmentItem))]

namespace CMS.CustomTables.Types.KDA
{
    /// <summary>
    /// Represents a content item of type IBTFAdjustmentItem.
    /// </summary>
    public partial class IBTFAdjustmentItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "KDA.IBTFAdjustment";


        /// <summary>
        /// The instance of the class that provides extended API for working with IBTFAdjustmentItem fields.
        /// </summary>
        private readonly IBTFAdjustmentItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// SKUID.
        /// </summary>
        [DatabaseField]
        public int SKUID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SKUID"), 0);
            }
            set
            {
                SetValue("SKUID", value);
            }
        }


        /// <summary>
        /// User ID.
        /// </summary>
        [DatabaseField]
        public int UserID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("UserID"), 0);
            }
            set
            {
                SetValue("UserID", value);
            }
        }


        /// <summary>
        /// Campaign ID.
        /// </summary>
        [DatabaseField]
        public int CampaignID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("CampaignID"), 0);
            }
            set
            {
                SetValue("CampaignID", value);
            }
        }


        /// <summary>
        /// Ordered Quantity.
        /// </summary>
        [DatabaseField]
        public int OrderedQuantity
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("OrderedQuantity"), 1);
            }
            set
            {
                SetValue("OrderedQuantity", value);
            }
        }


        /// <summary>
        /// Ordered Product Price.
        /// </summary>
        [DatabaseField]
        public decimal OrderedProductPrice
        {
            get
            {
                return ValidationHelper.GetDecimal(GetValue("OrderedProductPrice"), ValidationHelper.GetDecimal("0", 0));
            }
            set
            {
                SetValue("OrderedProductPrice", value);
            }
        }


        /// <summary>
        /// Site Name.
        /// </summary>
        [DatabaseField]
        public string SiteName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SiteName"), "");
            }
            set
            {
                SetValue("SiteName", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with IBTFAdjustmentItem fields.
        /// </summary>
        [RegisterProperty]
        public IBTFAdjustmentItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with IBTFAdjustmentItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class IBTFAdjustmentItemFields : AbstractHierarchicalObject<IBTFAdjustmentItemFields>
        {
            /// <summary>
            /// The content item of type IBTFAdjustmentItem that is a target of the extended API.
            /// </summary>
            private readonly IBTFAdjustmentItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="IBTFAdjustmentItemFields" /> class with the specified content item of type IBTFAdjustmentItem.
            /// </summary>
            /// <param name="instance">The content item of type IBTFAdjustmentItem that is a target of the extended API.</param>
            public IBTFAdjustmentItemFields(IBTFAdjustmentItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// SKUID.
            /// </summary>
            public int SKUID
            {
                get
                {
                    return mInstance.SKUID;
                }
                set
                {
                    mInstance.SKUID = value;
                }
            }


            /// <summary>
            /// User ID.
            /// </summary>
            public int UserID
            {
                get
                {
                    return mInstance.UserID;
                }
                set
                {
                    mInstance.UserID = value;
                }
            }


            /// <summary>
            /// Campaign ID.
            /// </summary>
            public int CampaignID
            {
                get
                {
                    return mInstance.CampaignID;
                }
                set
                {
                    mInstance.CampaignID = value;
                }
            }


            /// <summary>
            /// Ordered Quantity.
            /// </summary>
            public int OrderedQuantity
            {
                get
                {
                    return mInstance.OrderedQuantity;
                }
                set
                {
                    mInstance.OrderedQuantity = value;
                }
            }


            /// <summary>
            /// Ordered Product Price.
            /// </summary>
            public decimal OrderedProductPrice
            {
                get
                {
                    return mInstance.OrderedProductPrice;
                }
                set
                {
                    mInstance.OrderedProductPrice = value;
                }
            }


            /// <summary>
            /// Site Name.
            /// </summary>
            public string SiteName
            {
                get
                {
                    return mInstance.SiteName;
                }
                set
                {
                    mInstance.SiteName = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="IBTFAdjustmentItem" /> class.
        /// </summary>
        public IBTFAdjustmentItem() : base(CLASS_NAME)
        {
            mFields = new IBTFAdjustmentItemFields(this);
        }

        #endregion
    }
}