//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(InboundTrackingItem.CLASS_NAME, typeof(InboundTrackingItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type InboundTrackingItem.
	/// </summary>
	public partial class InboundTrackingItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.InboundTracking";


		/// <summary>
		/// The instance of the class that provides extended API for working with InboundTrackingItem fields.
		/// </summary>
		private readonly InboundTrackingItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// 
		/// </summary>
		[DatabaseField]
		public bool IsClosed
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsClosed"), false);
			}
			set
			{
				SetValue("IsClosed", value);
			}
		}


		/// <summary>
		/// SKUID.
		/// </summary>
		[DatabaseField]
		public int SKUID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SKUID"), 0);
			}
			set
			{
				SetValue("SKUID", value);
			}
		}


		/// <summary>
		/// Qty Ordered.
		/// </summary>
		[DatabaseField]
		public int QtyOrdered
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("QtyOrdered"), 0);
			}
			set
			{
				SetValue("QtyOrdered", value);
			}
		}


		/// <summary>
		/// Demand Goal.
		/// </summary>
		[DatabaseField]
		public int DemandGoal
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("DemandGoal"), 0);
			}
			set
			{
				SetValue("DemandGoal", value);
			}
		}


		/// <summary>
		/// Qty Received.
		/// </summary>
		[DatabaseField]
		public int QtyReceived
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("QtyReceived"), 0);
			}
			set
			{
				SetValue("QtyReceived", value);
			}
		}


		/// <summary>
		/// Qty Produced.
		/// </summary>
		[DatabaseField]
		public int QtyProduced
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("QtyProduced"), 0);
			}
			set
			{
				SetValue("QtyProduced", value);
			}
		}


		/// <summary>
		/// Overage.
		/// </summary>
		[DatabaseField]
		public int Overage
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("Overage"), 0);
			}
			set
			{
				SetValue("Overage", value);
			}
		}


		/// <summary>
		/// Vendor.
		/// </summary>
		[DatabaseField]
		public string Vendor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Vendor"), "");
			}
			set
			{
				SetValue("Vendor", value);
			}
		}


		/// <summary>
		/// Exp Arrival To Cenveo.
		/// </summary>
		[DatabaseField]
		public string ExpArrivalToCenveo
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ExpArrivalToCenveo"), "");
			}
			set
			{
				SetValue("ExpArrivalToCenveo", value);
			}
		}


		/// <summary>
		/// Delivery To Dist By.
		/// </summary>
		[DatabaseField]
		public string DeliveryToDistBy
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DeliveryToDistBy"), "");
			}
			set
			{
				SetValue("DeliveryToDistBy", value);
			}
		}


		/// <summary>
		/// Shipped To Dist.
		/// </summary>
		[DatabaseField]
		public string ShippedToDist
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ShippedToDist"), "");
			}
			set
			{
				SetValue("ShippedToDist", value);
			}
		}


		/// <summary>
		/// Cenveo Comments.
		/// </summary>
		[DatabaseField]
		public string CenveoComments
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CenveoComments"), "");
			}
			set
			{
				SetValue("CenveoComments", value);
			}
		}


		/// <summary>
		/// Twe Comments.
		/// </summary>
		[DatabaseField]
		public string TweComments
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TweComments"), "");
			}
			set
			{
				SetValue("TweComments", value);
			}
		}


		/// <summary>
		/// Actual Price.
		/// </summary>
		[DatabaseField]
		public double ActualPrice
		{
			get
			{
				return ValidationHelper.GetDouble(GetValue("ActualPrice"), 0);
			}
			set
			{
				SetValue("ActualPrice", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with InboundTrackingItem fields.
		/// </summary>
		[RegisterProperty]
		public InboundTrackingItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with InboundTrackingItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class InboundTrackingItemFields : AbstractHierarchicalObject<InboundTrackingItemFields>
		{
			/// <summary>
			/// The content item of type InboundTrackingItem that is a target of the extended API.
			/// </summary>
			private readonly InboundTrackingItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="InboundTrackingItemFields" /> class with the specified content item of type InboundTrackingItem.
			/// </summary>
			/// <param name="instance">The content item of type InboundTrackingItem that is a target of the extended API.</param>
			public InboundTrackingItemFields(InboundTrackingItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// 
			/// </summary>
			public bool IsClosed
			{
				get
				{
					return mInstance.IsClosed;
				}
				set
				{
					mInstance.IsClosed = value;
				}
			}


			/// <summary>
			/// SKUID.
			/// </summary>
			public int SKUID
			{
				get
				{
					return mInstance.SKUID;
				}
				set
				{
					mInstance.SKUID = value;
				}
			}


			/// <summary>
			/// Qty Ordered.
			/// </summary>
			public int QtyOrdered
			{
				get
				{
					return mInstance.QtyOrdered;
				}
				set
				{
					mInstance.QtyOrdered = value;
				}
			}


			/// <summary>
			/// Demand Goal.
			/// </summary>
			public int DemandGoal
			{
				get
				{
					return mInstance.DemandGoal;
				}
				set
				{
					mInstance.DemandGoal = value;
				}
			}


			/// <summary>
			/// Qty Received.
			/// </summary>
			public int QtyReceived
			{
				get
				{
					return mInstance.QtyReceived;
				}
				set
				{
					mInstance.QtyReceived = value;
				}
			}


			/// <summary>
			/// Qty Produced.
			/// </summary>
			public int QtyProduced
			{
				get
				{
					return mInstance.QtyProduced;
				}
				set
				{
					mInstance.QtyProduced = value;
				}
			}


			/// <summary>
			/// Overage.
			/// </summary>
			public int Overage
			{
				get
				{
					return mInstance.Overage;
				}
				set
				{
					mInstance.Overage = value;
				}
			}


			/// <summary>
			/// Vendor.
			/// </summary>
			public string Vendor
			{
				get
				{
					return mInstance.Vendor;
				}
				set
				{
					mInstance.Vendor = value;
				}
			}


			/// <summary>
			/// Exp Arrival To Cenveo.
			/// </summary>
			public string ExpArrivalToCenveo
			{
				get
				{
					return mInstance.ExpArrivalToCenveo;
				}
				set
				{
					mInstance.ExpArrivalToCenveo = value;
				}
			}


			/// <summary>
			/// Delivery To Dist By.
			/// </summary>
			public string DeliveryToDistBy
			{
				get
				{
					return mInstance.DeliveryToDistBy;
				}
				set
				{
					mInstance.DeliveryToDistBy = value;
				}
			}


			/// <summary>
			/// Shipped To Dist.
			/// </summary>
			public string ShippedToDist
			{
				get
				{
					return mInstance.ShippedToDist;
				}
				set
				{
					mInstance.ShippedToDist = value;
				}
			}


			/// <summary>
			/// Cenveo Comments.
			/// </summary>
			public string CenveoComments
			{
				get
				{
					return mInstance.CenveoComments;
				}
				set
				{
					mInstance.CenveoComments = value;
				}
			}


			/// <summary>
			/// Twe Comments.
			/// </summary>
			public string TweComments
			{
				get
				{
					return mInstance.TweComments;
				}
				set
				{
					mInstance.TweComments = value;
				}
			}


			/// <summary>
			/// Actual Price.
			/// </summary>
			public double ActualPrice
			{
				get
				{
					return mInstance.ActualPrice;
				}
				set
				{
					mInstance.ActualPrice = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="InboundTrackingItem" /> class.
		/// </summary>
		public InboundTrackingItem() : base(CLASS_NAME)
		{
			mFields = new InboundTrackingItemFields(this);
		}

		#endregion
	}
}