//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(POSNumberItem.CLASS_NAME, typeof(POSNumberItem))]

namespace CMS.CustomTables.Types.KDA
{
    /// <summary>
    /// Represents a content item of type POSNumberItem.
    /// </summary>
    public partial class POSNumberItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "KDA.POSNumber";


        /// <summary>
        /// The instance of the class that provides extended API for working with POSNumberItem fields.
        /// </summary>
        private readonly POSNumberItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Brand ID.
        /// </summary>
        [DatabaseField]
        public int BrandID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("BrandID"), 0);
            }
            set
            {
                SetValue("BrandID", value);
            }
        }


        /// <summary>
        /// Year.
        /// </summary>
        [DatabaseField]
        public int Year
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("Year"), 0);
            }
            set
            {
                SetValue("Year", value);
            }
        }


        /// <summary>
        /// POSCode.
        /// </summary>
        [DatabaseField]
        public string POSCode
        {
            get
            {
                return ValidationHelper.GetString(GetValue("POSCode"), "");
            }
            set
            {
                SetValue("POSCode", value);
            }
        }


        /// <summary>
        /// POS Category ID.
        /// </summary>
        [DatabaseField]
        public int POSCategoryID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("POSCategoryID"), 0);
            }
            set
            {
                SetValue("POSCategoryID", value);
            }
        }


        /// <summary>
        /// POS Category Name.
        /// </summary>
        [DatabaseField]
        public string POSCategoryName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("POSCategoryName"), "");
            }
            set
            {
                SetValue("POSCategoryName", value);
            }
        }


        /// <summary>
        /// Brand Name.
        /// </summary>
        [DatabaseField]
        public string BrandName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("BrandName"), "");
            }
            set
            {
                SetValue("BrandName", value);
            }
        }


        /// <summary>
        /// POS Number.
        /// </summary>
        [DatabaseField]
        public string POSNumber
        {
            get
            {
                return ValidationHelper.GetString(GetValue("POSNumber"), "");
            }
            set
            {
                SetValue("POSNumber", value);
            }
        }


        /// <summary>
        /// Enable.
        /// </summary>
        [DatabaseField]
        public bool Enable
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("Enable"), true);
            }
            set
            {
                SetValue("Enable", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with POSNumberItem fields.
        /// </summary>
        [RegisterProperty]
        public POSNumberItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with POSNumberItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class POSNumberItemFields : AbstractHierarchicalObject<POSNumberItemFields>
        {
            /// <summary>
            /// The content item of type POSNumberItem that is a target of the extended API.
            /// </summary>
            private readonly POSNumberItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="POSNumberItemFields" /> class with the specified content item of type POSNumberItem.
            /// </summary>
            /// <param name="instance">The content item of type POSNumberItem that is a target of the extended API.</param>
            public POSNumberItemFields(POSNumberItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Brand ID.
            /// </summary>
            public int BrandID
            {
                get
                {
                    return mInstance.BrandID;
                }
                set
                {
                    mInstance.BrandID = value;
                }
            }


            /// <summary>
            /// Year.
            /// </summary>
            public int Year
            {
                get
                {
                    return mInstance.Year;
                }
                set
                {
                    mInstance.Year = value;
                }
            }


            /// <summary>
            /// POSCode.
            /// </summary>
            public string POSCode
            {
                get
                {
                    return mInstance.POSCode;
                }
                set
                {
                    mInstance.POSCode = value;
                }
            }


            /// <summary>
            /// POS Category ID.
            /// </summary>
            public int POSCategoryID
            {
                get
                {
                    return mInstance.POSCategoryID;
                }
                set
                {
                    mInstance.POSCategoryID = value;
                }
            }


            /// <summary>
            /// POS Category Name.
            /// </summary>
            public string POSCategoryName
            {
                get
                {
                    return mInstance.POSCategoryName;
                }
                set
                {
                    mInstance.POSCategoryName = value;
                }
            }


            /// <summary>
            /// Brand Name.
            /// </summary>
            public string BrandName
            {
                get
                {
                    return mInstance.BrandName;
                }
                set
                {
                    mInstance.BrandName = value;
                }
            }


            /// <summary>
            /// POS Number.
            /// </summary>
            public string POSNumber
            {
                get
                {
                    return mInstance.POSNumber;
                }
                set
                {
                    mInstance.POSNumber = value;
                }
            }


            /// <summary>
            /// Enable.
            /// </summary>
            public bool Enable
            {
                get
                {
                    return mInstance.Enable;
                }
                set
                {
                    mInstance.Enable = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="POSNumberItem" /> class.
        /// </summary>
        public POSNumberItem() : base(CLASS_NAME)
        {
            mFields = new POSNumberItemFields(this);
        }

        #endregion
    }
}