//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables.Types.KDA;
using CMS.CustomTables;

[assembly: RegisterCustomTable(ProductItemSpecsItem.CLASS_NAME, typeof(ProductItemSpecsItem))]

namespace CMS.CustomTables.Types.KDA
{
	/// <summary>
	/// Represents a content item of type ProductItemSpecsItem.
	/// </summary>
	public partial class ProductItemSpecsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.ProductItemSpecs";


		/// <summary>
		/// The instance of the class that provides extended API for working with ProductItemSpecsItem fields.
		/// </summary>
		private readonly ProductItemSpecsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Item Spec.
		/// </summary>
		[DatabaseField]
		public string ItemSpec
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ItemSpec"), "");
			}
			set
			{
				SetValue("ItemSpec", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ProductItemSpecsItem fields.
		/// </summary>
		[RegisterProperty]
		public ProductItemSpecsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ProductItemSpecsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ProductItemSpecsItemFields : AbstractHierarchicalObject<ProductItemSpecsItemFields>
		{
			/// <summary>
			/// The content item of type ProductItemSpecsItem that is a target of the extended API.
			/// </summary>
			private readonly ProductItemSpecsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ProductItemSpecsItemFields" /> class with the specified content item of type ProductItemSpecsItem.
			/// </summary>
			/// <param name="instance">The content item of type ProductItemSpecsItem that is a target of the extended API.</param>
			public ProductItemSpecsItemFields(ProductItemSpecsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Item Spec.
			/// </summary>
			public string ItemSpec
			{
				get
				{
					return mInstance.ItemSpec;
				}
				set
				{
					mInstance.ItemSpec = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ProductItemSpecsItem" /> class.
		/// </summary>
		public ProductItemSpecsItem() : base(CLASS_NAME)
		{
			mFields = new ProductItemSpecsItemFields(this);
		}

		#endregion
	}
}