//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.KDA;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(CampaignProduct.CLASS_NAME, typeof(CampaignProduct))]

namespace CMS.DocumentEngine.Types.KDA
{
	/// <summary>
	/// Represents a content item of type CampaignProduct.
	/// </summary>
	public partial class CampaignProduct : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.CampaignProduct";


		/// <summary>
		/// The instance of the class that provides extended API for working with CampaignProduct fields.
		/// </summary>
		private readonly CampaignProductFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CampaignProductsID.
		/// </summary>
		[DatabaseIDField]
		public int CampaignProductID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CampaignProductID"), 0);
			}
			set
			{
				SetValue("CampaignProductID", value);
			}
		}


		/// <summary>
		/// POS# Number.
		/// </summary>
		[DatabaseField]
		public int POSNumber
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("POSNumber"), 0);
			}
			set
			{
				SetValue("POSNumber", value);
			}
		}


		/// <summary>
		/// Program ID.
		/// </summary>
		[DatabaseField]
		public int ProgramID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ProgramID"), 0);
			}
			set
			{
				SetValue("ProgramID", value);
			}
		}


		/// <summary>
		/// Product Name.
		/// </summary>
		[DatabaseField]
		public string ProductName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ProductName"), "");
			}
			set
			{
				SetValue("ProductName", value);
			}
		}


		/// <summary>
		/// Brand Name.
		/// </summary>
		[DatabaseField]
		public int BrandID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BrandID"), 0);
			}
			set
			{
				SetValue("BrandID", value);
			}
		}


		/// <summary>
		/// Estimated Price.
		/// </summary>
		[DatabaseField]
		public string EstimatedPrice
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EstimatedPrice"), "");
			}
			set
			{
				SetValue("EstimatedPrice", value);
			}
		}


		/// <summary>
		/// Actual Price.
		/// </summary>
		[DatabaseField]
		public string ActualPrice
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ActualPrice"), "");
			}
			set
			{
				SetValue("ActualPrice", value);
			}
		}


		/// <summary>
		/// Short Description.
		/// </summary>
		[DatabaseField]
		public string ShortDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ShortDescription"), "");
			}
			set
			{
				SetValue("ShortDescription", value);
			}
		}


		/// <summary>
		/// Long Description.
		/// </summary>
		[DatabaseField]
		public string LongDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LongDescription"), "");
			}
			set
			{
				SetValue("LongDescription", value);
			}
		}


		/// <summary>
		/// State.
		/// </summary>
		[DatabaseField]
		public string State
		{
			get
			{
				return ValidationHelper.GetString(GetValue("State"), "");
			}
			set
			{
				SetValue("State", value);
			}
		}


		/// <summary>
		/// Expiration Date.
		/// </summary>
		[DatabaseField]
		public DateTime ExpirationDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("ExpirationDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("ExpirationDate", value);
			}
		}


		/// <summary>
		/// Category .
		/// </summary>
		[DatabaseField]
		public int CategoryID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CategoryID"), 0);
			}
			set
			{
				SetValue("CategoryID", value);
			}
		}

		/// <summary>
		/// Status.
		/// </summary>
		[DatabaseField]
		public bool Status
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("Status"), true);
			}
			set
			{
				SetValue("Status", value);
			}
		}


		/// <summary>
		/// Item Specs.
		/// </summary>
		[DatabaseField]
		public string ItemSpecs
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ItemSpecs"), "");
			}
			set
			{
				SetValue("ItemSpecs", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public Guid Image
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Image"), Guid.Empty);
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CampaignProduct fields.
		/// </summary>
		[RegisterProperty]
		public CampaignProductFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CampaignProduct fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CampaignProductFields : AbstractHierarchicalObject<CampaignProductFields>
		{
			/// <summary>
			/// The content item of type CampaignProduct that is a target of the extended API.
			/// </summary>
			private readonly CampaignProduct mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CampaignProductFields" /> class with the specified content item of type CampaignProduct.
			/// </summary>
			/// <param name="instance">The content item of type CampaignProduct that is a target of the extended API.</param>
			public CampaignProductFields(CampaignProduct instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CampaignProductsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CampaignProductID;
				}
				set
				{
					mInstance.CampaignProductID = value;
				}
			}


			/// <summary>
			/// POS# Number.
			/// </summary>
			public int POSNumber
			{
				get
				{
					return mInstance.POSNumber;
				}
				set
				{
					mInstance.POSNumber = value;
				}
			}


			/// <summary>
			/// Program ID.
			/// </summary>
			public int ProgramID
			{
				get
				{
					return mInstance.ProgramID;
				}
				set
				{
					mInstance.ProgramID = value;
				}
			}


			/// <summary>
			/// Product Name.
			/// </summary>
			public string ProductName
			{
				get
				{
					return mInstance.ProductName;
				}
				set
				{
					mInstance.ProductName = value;
				}
			}


			/// <summary>
			/// Brand Name.
			/// </summary>
			public int BrandID
			{
				get
				{
					return mInstance.BrandID;
				}
				set
				{
					mInstance.BrandID = value;
				}
			}


			/// <summary>
			/// Estimated Price.
			/// </summary>
			public string EstimatedPrice
			{
				get
				{
					return mInstance.EstimatedPrice;
				}
				set
				{
					mInstance.EstimatedPrice = value;
				}
			}


			/// <summary>
			/// Actual Price.
			/// </summary>
			public string ActualPrice
			{
				get
				{
					return mInstance.ActualPrice;
				}
				set
				{
					mInstance.ActualPrice = value;
				}
			}


			/// <summary>
			/// Short Description.
			/// </summary>
			public string ShortDescription
			{
				get
				{
					return mInstance.ShortDescription;
				}
				set
				{
					mInstance.ShortDescription = value;
				}
			}


			/// <summary>
			/// Long Description.
			/// </summary>
			public string LongDescription
			{
				get
				{
					return mInstance.LongDescription;
				}
				set
				{
					mInstance.LongDescription = value;
				}
			}


			/// <summary>
			/// State.
			/// </summary>
			public string State
			{
				get
				{
					return mInstance.State;
				}
				set
				{
					mInstance.State = value;
				}
			}


			/// <summary>
			/// Expiration Date.
			/// </summary>
			public DateTime ExpirationDate
			{
				get
				{
					return mInstance.ExpirationDate;
				}
				set
				{
					mInstance.ExpirationDate = value;
				}
			}


			/// <summary>
			/// Category .
			/// </summary>
			public int CategoryID
			{
				get
				{
					return mInstance.CategoryID;
				}
				set
				{
					mInstance.CategoryID = value;
				}
			}


			


			/// <summary>
			/// Status.
			/// </summary>
			public bool Status
			{
				get
				{
					return mInstance.Status;
				}
				set
				{
					mInstance.Status = value;
				}
			}


			/// <summary>
			/// Item Specs.
			/// </summary>
			public string ItemSpecs
			{
				get
				{
					return mInstance.ItemSpecs;
				}
				set
				{
					mInstance.ItemSpecs = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public Guid Image
			{
				get
				{
					return mInstance.Image;
				}
				set
				{
					mInstance.Image = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CampaignProduct" /> class.
		/// </summary>
		public CampaignProduct() : base(CLASS_NAME)
		{
			mFields = new CampaignProductFields(this);
		}

		#endregion
	}
}