//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.KDA;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Campaign.CLASS_NAME, typeof(Campaign))]

namespace CMS.DocumentEngine.Types.KDA
{
	/// <summary>
	/// Represents a content item of type Campaign.
	/// </summary>
	public partial class Campaign : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "KDA.Campaign";


		/// <summary>
		/// The instance of the class that provides extended API for working with Campaign fields.
		/// </summary>
		private readonly CampaignFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CampaignID.
		/// </summary>
		[DatabaseIDField]
		public int CampaignID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CampaignID"), 0);
			}
			set
			{
				SetValue("CampaignID", value);
			}
		}


		/// <summary>
		/// Campaign Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), "");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Campaign Description.
		/// </summary>
		[DatabaseField]
		public string Description
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Description"), "");
			}
			set
			{
				SetValue("Description", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Campaign fields.
		/// </summary>
		[RegisterProperty]
		public CampaignFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Campaign fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CampaignFields : AbstractHierarchicalObject<CampaignFields>
		{
			/// <summary>
			/// The content item of type Campaign that is a target of the extended API.
			/// </summary>
			private readonly Campaign mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CampaignFields" /> class with the specified content item of type Campaign.
			/// </summary>
			/// <param name="instance">The content item of type Campaign that is a target of the extended API.</param>
			public CampaignFields(Campaign instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CampaignID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CampaignID;
				}
				set
				{
					mInstance.CampaignID = value;
				}
			}


			/// <summary>
			/// Campaign Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Campaign Description.
			/// </summary>
			public string Description
			{
				get
				{
					return mInstance.Description;
				}
				set
				{
					mInstance.Description = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Campaign" /> class.
		/// </summary>
		public Campaign() : base(CLASS_NAME)
		{
			mFields = new CampaignFields(this);
		}

		#endregion
	}
}